[package]
name = "stratus"
version.workspace = true
edition.workspace = true

[dependencies]
stratus-auth = { path = "../stratus-auth" }

async-stream = "0.3"
dashmap = "6"
governor = { version = "0.10", features = ["std", "dashmap"] }
axum = { version = "0.8.6", features = ["http2"] }
axum-server = { version = "0.7.2", features = ["rustls", "tls-rustls"] }
rcgen = "0.13"
rustls = "0.23"
rustls-pemfile = "2"
tokio-rustls = "0.26"
x509-parser = "0.16"
argon2.workspace = true
base64 = "0.22"
chrono = "0.4"
color-eyre = "0.6.5"
dotenvy = "0.15.7"
eyre.workspace = true
futures = "0.3"
glob = "0.3"
html-escape = "0.2"
http = "1"
http-range-header = "0.4"
humansize = "2.1"
listenfd = "1.0.2"
mime_guess = "2.0"
notify = "8.2.0"
serde.workspace = true
socket2 = { version = "0.5", features = ["all"] }
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = { version = "0.1", features = ["fs"] }
tokio-util = { version = "0.7", features = ["io"] }
toml = "0.9.8"
tower = { version = "0.5.2", features = ["full"] }
tower-http = { version = "0.6.6", features = [
    "compression-br",
    "compression-gzip",
    "compression-zstd",
    "cors",
    "decompression-br",
    "decompression-gzip",
    "decompression-zstd",
    "limit",
    "fs",
] }
tracing = { version = "0.1.41", features = ["release_max_level_debug", "log"] }
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.20", features = [
    "chrono",
    "serde",
    "json",
    "env-filter",
] }
urlencoding = "2.1"
metrics = "0.24"
metrics-exporter-prometheus = "0.17.2"
thiserror = "2.0"

[dev-dependencies]
flate2 = "1.1.4"
http = "1"
zstd = "0.13.3"
tempfile = "3.14"
